#!/usr/bin/python

import socket
dominio = 'ufo.com.br'
with open('/root/brute force.txt') as arquivo:
    nomes = arquivo.readlines()
for nome in nomes:
    DNS = nome.strip('\n') + '.' + dominio
    try:
        print DNS + ': ' + socket.gethostbyname(DNS)
    except socket.gaierror:
        pass
