#!/usr/bin/python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = ''
porta  = 23

msg = raw_input('mensagem')

s.bind((host, porta))
s.listen(30)

while True:
	c, e = s.accept()
	print('Conectado com', e)
	c.send(msg.encode('ascii'))
	c.close

