#!/usr/bin/python
# -*- coding: utf-8 -*-
 
import socket
dominio = raw_input('site:')
nomes = ['ns1', 'ns2', 'www', 'ftp', 'intranet', 'ssh']
for nome in nomes:
	DNS =nome + '.' + dominio
	try:
		print DNS + ':' + socket.gethostbyname(DNS)
	except socket.gaierror:
		pass

